services:
  database:
    image: mysql:5.7
    # depends_on:
    #   - db
    container_name: database # this or the logical service name must be 'database' to match the api's requirements
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - books-net
    volumes:
      - mysql-volume:/var/lib/mysql

  bookstore:
    # image: bookstore-api
    build: .  # requires docker-compose up --build to work
    container_name: bookstore
    networks:
      - books-net
    ports:
      - 80:80
    depends_on:
      - database
    restart: always

volumes:
  mysql-volume:

networks:
  books-net: